Repository halimkun/rsia-api-v2, pull requests merged in 2024-04, with the labels that each got.

#5 Test protection
  README.md
Labels: good first issue

#10 Pencarian dan Filter Data Surat eksternal
  app/Http/Controllers/v2/RsiaSuratEksternalController.php
  app/Models/RsiaSuratEksternal.php
  app/Services/GetFilterData.php
  routes/partials/berkas.php
Labels: enhancement

#12 Endpoint Surat masuk
  .env.example
  app/Http/Controllers/v2/RsiaSuratMasukController.php
  app/Models/RsiaSuratMasuk.php
  app/Providers/AppServiceProvider.php
  composer.json
  composer.lock
  config/filesystems.php
  routes/partials/berkas.php
Labels: enhancement, dependencies

#21 Photo Upload & Fix DB Transaction BUG
  app/Http/Controllers/v2/PegawaiController.php
Labels: enhancement

#22 Undangan dan kehadiran
  app/Http/Controllers/v2/RsiaKehadiranRapatController.php
  app/Http/Controllers/v2/RsiaPenerimaUndanganController.php
  app/Http/Controllers/v2/RsiaSuratInternalController.php
  app/Http/Resources/Undangan/CompleteCollection.php
  app/Http/Resources/Undangan/Penerima/CompleteCollection.php
  app/Models/RsiaKehadiranRapat.php
  app/Models/RsiaPenerimaUndangan.php
  composer.json
  composer.lock
  routes/partials/undangan.php
Labels: enhancement, dependencies

#26 Endpoint Berkas Komite PMKP
  app/Helpers/komite/LastNomor.php
  app/Http/Controllers/v2/RsiaBerkasKomitePmkpController.php
  app/Http/Controllers/v2/RsiaKehadiranRapatController.php
  app/Http/Controllers/v2/RsiaPenerimaUndanganController.php
  app/Http/Resources/Berkas/Komite/CompleteCollection.php
  app/Http/Resources/Berkas/Komite/CompleteResource.php
  app/Models/RsiaBerkasKomitePmkp.php
  routes/partials/berkas.php
Labels: enhancement

#27 Endpoint Berkas Komite PPI
  app/Http/Controllers/v2/RsiaBerkasKomitePpiController.php
  app/Models/RsiaBerkasKomitePpi.php
  routes/partials/berkas.php
Labels: enhancement

#28 Endpoint Berkas Komite Medis
  app/Http/Controllers/v2/RsiaBerkasKomiteMedisController.php
  app/Models/RsiaBerkasKomiteMedis.php
  routes/partials/berkas.php
Labels: enhancement

#29 Update Komite Medis
  app/Http/Controllers/Orion/RsiaBerkasKomiteMedisController.php
  app/Models/RsiaBerkasKomiteMedis.php
  config/orion.php
  routes/partials/berkas.php
Labels: bug, enhancement

#31 Endpoint Berkas Komite Kesehatan
  app/Http/Controllers/Orion/RsiaBerkasKomiteKesehatanController.php
  app/Http/Controllers/v2/RsiaBerkasKomiteKesehatanController.php
  app/Models/RsiaBerkasKomiteKesehatan.php
  routes/partials/berkas.php
Labels: enhancement

#36 Pasien Rawat Inap
  app/Http/Controllers/Orion/PasienRawatInapController.php
  app/Http/Controllers/v2/PasienRawatInapController.php
  app/Http/Resources/Pasien/Ranap/CompleteCollection.php
  app/Http/Resources/Pasien/Ranap/PasieCollection.php
  app/Http/Resources/Pasien/Ranap/PasieResource.php
  app/Models/KamarInap.php
  app/Models/RegPeriksa.php
  routes/partials/pasien.php
Labels: enhancement

#38 Endpoint Data Pasien
  app/Http/Controllers/Orion/PasienController.php
  app/Http/Controllers/v2/PasienController.php
  app/Http/Resources/Pasien/PasienCollection.php
  app/Http/Resources/Pasien/PasienResource.php
  app/Http/Resources/Pasien/Ranap/PasieRanapCollection.php
  app/Http/Resources/Pasien/Ranap/PasieRanapResource.php
  routes/partials/pasien.php
Labels: enhancement

#40 Tarif Pasien Rawat Inap
  app/Http/Controllers/v2/TarifPasienRawatInap.php
  app/Http/Resources/Pasien/Tarif/RunningTarif.php
  app/Http/Resources/Pasien/Tarif/TarifDetailPemberianObat.php
  app/Http/Resources/Pasien/Tarif/TarifKamarInap.php
  app/Http/Resources/Pasien/Tarif/TarifOperasi.php
  app/Http/Resources/Pasien/Tarif/TarifPeriksaLab.php
  app/Http/Resources/Pasien/Tarif/TarifPeriksaRadiologi.php
  app/Http/Resources/Pasien/Tarif/TarifRawatInapDr.php
  app/Http/Resources/Pasien/Tarif/TarifRawatInapDrPr.php
  app/Http/Resources/Pasien/Tarif/TarifRawatInapPr.php
  app/Http/Resources/Pasien/Tarif/TarifRawatJalanDr.php
  app/Http/Resources/Pasien/Tarif/TarifRawatJalanDrPr.php
  app/Http/Resources/Pasien/Tarif/TarifRawatJalanPr.php
  app/Models/DetailPemberianObat.php
  app/Models/Operasi.php
  app/Models/PeriksaLab.php
  app/Models/PeriksaRadiologi.php
  app/Models/RawatInapDr.php
  app/Models/RawatInapDrPr.php
  app/Models/RawatInapPr.php
  app/Models/RawatJalanDr.php
  app/Models/RawatJalanDrPr.php
  app/Models/RawatJalanPr.php
  routes/partials/pasien.php
Labels: enhancement

#42 Filetrack App Menu
  app/Http/Controllers/v2/RsiaMasterMenuFiletrackController.php
  app/Http/Middleware/UserMiddleware.php
  app/Http/Resources/User/Menu/MenuCollection.php
  app/Models/RsiaMasterMenuFiletrack.php
  app/Models/RsiaSetMenuFiletrack.php
  routes/partials/berkas.php
  routes/partials/pasien.php
  routes/partials/pegawai.php
  routes/partials/undangan.php
  routes/partials/user.php
Labels: enhancement

#43 Endpoint Pasien Rawat Jalan
  app/Http/Controllers/Orion/PasienRawatJalanController.php
  app/Http/Controllers/v2/PasienRawatJalanController.php
  app/Models/RegPeriksa.php
  routes/partials/pasien.php
Labels: enhancement
